export const pricingPlans = [
    {
        title: "Specter Plan (Free)",
        price: "$0",
        description:
            "Perfect for those who enjoy occasional horror stories and want to explore our collection.",
        features: [
            "Access to free stories",
            "Read 5 premium stories per month",
            "Access to user comments",
            "Email notifications for new stories",
            "Standard customer support",
        ],
    },
    {
        title: "Phantom Plan",
        monthlyPrice: { usd: "$4.99", eur: "4.99€" },
        annualPrice: { usd: "$49.99", eur: "49.99€" },
        description:
            "Ideal for horror enthusiasts who want more extensive access to our library.",
        features: [
            "Access to free stories",
            "Read 20 premium stories per month",
            "Access to user comments",
            "Email notifications for new stories",
            "Standard customer support",
            "Unlimited access to free stories",
            "Priority customer support",
            "Access to exclusive stories",
            "Create and share story playlists",
        ],
        mostPopular: true,
    },
    {
        title: "Poltergeist Plan",
        monthlyPrice: { usd: "$9.99", eur: "9.99€" },
        annualPrice: { usd: "$99.99", eur: "99.99€" },
        description:
            "Designed for horror aficionados who want the ultimate experience with full access and advanced features.",
        features: [
            "Access to free stories",
            "Read 5 premium stories per month",
            "Access to user comments",
            "Email notifications for new stories",
            "Standard customer support",
            "Unlimited access to free stories",
            "Read 20 premium stories per month",
            "Priority customer support",
            "Access to exclusive stories",
            "Create and share story playlists",
            "Read unlimited premium stories",
            "Email and SMS notifications for new stories and events",
            "Priority and dedicated customer support",
            "Special events access",
            "Early access to new stories",
            "Offline reading",
            "Exclusive forum",
        ],
    },
]

export const allFeatures = [
    "Access to free stories",
    "Read 5 premium stories per month",
    "Access to user comments",
    "Email notifications for new stories",
    "Standard customer support",
    "Unlimited access to free stories",
    "Read 20 premium stories per month",
    "Priority customer support",
    "Access to exclusive stories",
    "Create and share story playlists",
    "Read unlimited premium stories",
    "Email and SMS notifications for new stories and events",
    "Priority and dedicated customer support",
    "Special events access",
    "Early access to new stories",
    "Offline reading",
    "Exclusive forum",
]
