import Footer from "@/components/layout/Footer"
import Navbar from "@/components/layout/Navbar"
import type { Metadata } from "next"

export const metadata: Metadata = {
    title: "Creepify",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Navbar />
            {children}
            <Footer />
        </>
    )
}
